// 1. Require the package first
const dotenv = require('dotenv');
const path = require('path');

// 2. Configure it (pointing to the correct location of your .env file)
dotenv.config({ path: path.join(__dirname, '../.env') });

// 3. Now you can safely require your models
const mongoose = require('mongoose');
const Product = require('../models/product');
const User = require('../models/User');
const StyleProfile = require('../models/StyleProfile');


dotenv.config();

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    console.log('Connected to MongoDB for seeding!');

    await Product.deleteMany({});
    await User.deleteMany({});
    await StyleProfile.deleteMany({});

    const sampleProducts = [
      // 1-10 Kurtis (Real Myntra links)
      { name: "Sangria Embroidered Short Kurti", gender: "women", category: "kurti", categoryGroup: "upper", color: "black", fit: "regular", occasion: ["festive"], price: 575, styleCategory: "ethnic", compatibleColors: ["beige", "gold", "cream"], compatibleTypes: ["palazzo", "legging"], trendScore: 8, season: "summer", isTrending: true, imageUrl: "https://files.catbox.moe/5wpi9o.jpg", buyUrl: "https://www.myntra.com/kurtis/sangria/sangria-black-embroidered-short-kurti/39407274/buy" },
      { name: "ANEKYA Floral Print Pure Cotton Kurti", gender: "women", category: "kurti", categoryGroup: "upper", color: "black", fit: "regular", occasion: ["casual", "festive"], price: 571, styleCategory: "ethnic", compatibleColors: ["white", "grey", "black"], compatibleTypes: ["palazzo", "legging"], trendScore: 9, season: "summer", isTrending: true, imageUrl: "https://files.catbox.moe/p22872.jpg", buyUrl: "https://www.myntra.com/kurtis/anekya/anekya-floral-printed-flared-sleeves-pure-cotton-kurti/33696562/buy" },
      { name: "KALINI Mandarin Collar Tunic", gender: "women", category: "kurti", categoryGroup: "upper", color: "brown", fit: "regular", occasion: ["casual"], price: 667, styleCategory: "ethnic", compatibleColors: ["beige", "gold"], compatibleTypes: ["legging"], trendScore: 7, season: "all", isTrending: false, imageUrl: "https://files.catbox.moe/125v5e.jpg", buyUrl: "https://www.myntra.com/kurtis/kalini/kalini-women-floral-embroidered-mandarin-collar-tunic/36202560/buy" },
      { name: "Anouk Rustic Geometric Print Kurti", gender: "women", category: "kurti", categoryGroup: "upper", color: "maroon", fit: "regular", occasion: ["casual"], price: 394, styleCategory: "ethnic", compatibleColors: ["white", "gold", "black"], compatibleTypes: ["palazzo"], trendScore: 8, season: "summer", isTrending: true, imageUrl: "https://files.catbox.moe/v3mppq.jpg", buyUrl: "https://www.myntra.com/kurtis/anouk/anouk-rustic-geometric-print-tie-up-neck-crepe-kurti/40056459/buy" },
      { name: "Rain & Rainbow Printed Pure Cotton Kurti", gender: "women", category: "kurti", categoryGroup: "upper", color: "purple", fit: "regular", occasion: ["casual"], price: 957, styleCategory: "ethnic", compatibleColors: ["black", "brown", "white"], compatibleTypes: ["palazzo", "legging"], trendScore: 7, season: "summer", isTrending: true, imageUrl: "https://files.catbox.moe/lsgrcp.jpg", buyUrl: "https://www.myntra.com/kurtis/rain-rainbow/rain--rainbow-ethnic-motifs-printed-pure-cotton-kurti/25766698/buy" },


      { name: "Roadster Women Striped Shirt", gender: "women", category: "shirt", categoryGroup: "upper", color: "pink", fit: "regular", occasion: ["casual"], price: 336, styleCategory: "safe", compatibleColors: ["black", "navy"], compatibleTypes: ["jeans"], trendScore: 7, season: "all", isTrending: false, imageUrl: "https://files.catbox.moe/l3g14u.jpg", buyUrl: "https://www.flipkart.com/roadster-women-striped-casual-pink-shirt/p/itm0d49203def76d?pid=SHTHFFTGS8D4HAHQ&lid=LSTSHTHFFTGS8D4HAHQVIGC5V&marketplace=FLIPKART&q=roadster-women-striped-shirt&store=clo%2Fash%2Faxc%2Fvop&srno=s_1_3&otracker=search&otracker1=search&fm=Search&iid=e54dc3b7-c835-46c4-9b48-63dcd15d2c58.SHTHFFTGS8D4HAHQ.SEARCH&ppt=sp&ppn=sp&ssid=3svi8j82yo0000001771870721498&qH=3c356acb6a77a64c&ov_redirect=true" },
      //hoodies

      {
        name: 'H&M Men Black Relaxed Fit Hoodie',
        gender: "men",
        category: 'hoodie',
        categoryGroup: 'outerwear',
        color: 'black',
        fit: 'relaxed',
        occasion: ['casual'],
        price: 1499,
        styleCategory: 'bold',
        compatibleColors: ['grey', 'white', 'navy', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser', 'sweater'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/m1piow.png',
        buyUrl: 'https://www.myntra.com/sweatshirts/h&m/hm-men-black-relaxed-fit-hoodie/15193748/buy'
      },
      {
        name: 'Campus Sutra Men Grey Hooded Sweatshirt',
        gender: "men",
        category: 'hoodie',
        categoryGroup: 'outerwear',
        color: 'grey',
        fit: 'regular',
        occasion: ['casual'],
        price: 951,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'white', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser', 'sweater'],
        trendScore: 8,
        season: 'winter',
        isTrending: true,
        imageUrl: "https://files.catbox.moe/986ofj.png",
        buyUrl: 'https://www.myntra.com/sweatshirts/campussutra/campus-sutra-men-grey-hooded-sweatshirt/19746722/buy',
      },
      {
        name: 'Roadster Men Navy Blue Solid Hooded Sweatshirt',
        gender: "men",
        category: 'hoodie',
        categoryGroup: 'outerwear',
        color: 'navy',
        fit: 'regular',
        occasion: ['casual'],
        price: 364,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'black', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser', 'sweater'],
        trendScore: 8,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/qct30f.png',
        buyUrl: 'https://www.myntra.com/sweatshirts/roadster/roadster-men-navy-blue-solid-hooded-sweatshirt/11959342/buy'
      },
      {
        name: 'Snitch Men Olive Green Cotton Hooded Sweatshirt',
        gender: "men",
        category: 'hoodie',
        categoryGroup: 'outerwear',
        color: 'olive',
        fit: 'regular',
        occasion: ['casual'],
        price: 3998,
        styleCategory: 'trendy',
        compatibleColors: ['black', 'grey', 'brown', 'navy'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/xx2hnq.png',
        buyUrl: 'https://www.myntra.com/sweatshirts/snitch/snitch-men-olive-green-cotton-hooded-sweatshirt/20714164/buy'
      },
      //sweaters
      {
        name: 'Mast & Harbour Men Black Solid Sweater',
        gender: "men",
        category: 'sweater',
        categoryGroup: 'outerwear',
        color: 'black',
        fit: 'regular',
        occasion: ['casual', 'winter'],
        price: 1499,
        styleCategory: 'bold',
        compatibleColors: ['white', 'grey', 'navy', 'olive', 'maroon'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/5zjg6f.png',
        buyUrl: 'https://www.myntra.com/sweaters/mast--harbour/mast--harbour-men-black-solid-sweater/9298991/buy'
      },
      {
        name: 'Roadster Men Grey Solid Pullover Sweater',
        gender: "men",
        category: 'sweater',
        categoryGroup: 'outerwear',
        color: 'grey',
        fit: 'regular',
        occasion: ['casual', 'winter'],
        price: 999,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'white', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['tshirt', 'shirt', 'jeans', 'jogger', 'cargo', 'trouser'],
        trendScore: 8,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/ofzouf.png',
        buyUrl: 'https://www.myntra.com/sweaters/roadster/roadster-men-grey-solid-pullover-sweater/5151876/buy'

      },


      //jackets

      {
        name: 'Fort Collins Men Black Solid Bomber Jacket',
        gender: "men",
        category: 'jacket',
        categoryGroup: 'outerwear',
        color: 'black',
        fit: 'regular',
        occasion: ['casual'],
        price: 1795,
        styleCategory: 'bold',
        compatibleColors: ['white', 'grey', 'navy', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['shirt', 'tshirt', 'jeans', 'jogger', 'cargo'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/ie3qcj.png',
        buyUrl: 'https://www.myntra.com/jackets/fort-collins/fort-collins-men-black-solid-bomber-jacket/7692476/buy'

      },
      {
        name: 'OVS Men Navy Solid Slim Fit Bomber Jacket',
        gender: "men",
        category: 'jacket',
        categoryGroup: 'outerwear',
        color: 'navy',
        fit: 'slim',
        occasion: ['casual'],
        price: 2299,
        styleCategory: 'bold',
        compatibleColors: ['white', 'grey', 'black'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['shirt', 'tshirt', 'jeans', 'jogger', 'cargo'],
        trendScore: 8,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/gfojr0.png',
        buyUrl: 'https://www.myntra.com/jackets/ovs/ovs-men-navy-solid-slim-fit-bomber-jacket/2135731/buy'
      },
      {
        name: 'Fort Collins Men Olive Green Solid Tailored Jacket',
        gender: "men",
        category: 'jacket',
        categoryGroup: 'outerwear',
        color: 'olive',
        fit: 'regular',
        occasion: ['casual'],
        price: 2499,
        styleCategory: 'bold',
        compatibleColors: ['black', 'white', 'brown'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['shirt', 'tshirt', 'jeans', 'jogger', 'cargo'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/lrdnov.png',
        buyUrl: 'https://www.myntra.com/jackets/fort-collins/fort-collins-men-olive-green-solid-tailored-jacket/10498304/buy'
      },


      {
        name: 'SINGLE Men Black Solid Slim Fit Joggers',
        gender: "men",
        category: 'jogger',
        categoryGroup: 'lower',
        color: 'black',
        fit: 'slim',
        occasion: ['casual'],
        price: 2199,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'navy', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['shirt', 'tshirt', 'jacket'],
        trendScore: 8,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/bt0puu.png',
        buyUrl: 'https://www.myntra.com/track-pants/single/single-men-black-solid-slim-fit-joggers/11433382/buy'
      },

      {
        name: 'H&M Men Black Shorts',
        gender: "men",
        category: 'shorts',
        categoryGroup: 'lower',
        color: 'black',
        fit: 'regular',
        occasion: ['casual'],
        price: 1199,
        styleCategory: 'safe',
        compatibleColors: ['white', 'navy', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['tshirt'],
        trendScore: 7,
        season: 'summer',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/svfi88.png',
        buyUrl: 'https://www.myntra.com/shorts/hm/hm-men-black-shorts/20515086/buy'
      },
      //trousers
      {
        name: 'Peter England Men Black Slim Fit Formal Trousers',
        gender: "men",
        category: 'trouser',
        categoryGroup: 'lower',
        color: 'black',
        fit: 'slim',
        occasion: ['formal'],
        price: 1799,
        styleCategory: 'safe',
        compatibleColors: ['white', 'navy', 'grey'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['shirt', 'formal shirt', 'jacket'],
        trendScore: 7,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/fwr8dz.png',
        buyUrl: 'https://www.myntra.com/trousers/peter-england/peter-england-men-black-slim-fit-formal-trousers/14219580/buy'
      },

      {
        name: 'Snitch Men Black Mid-Rise Relaxed Fit Cargo Trousers',
        gender: "men",
        category: 'cargo',
        categoryGroup: 'lower',
        color: 'black',
        fit: 'relaxed',
        occasion: ['casual'],
        price: 1699,
        styleCategory: 'trendy',
        compatibleColors: ['white', 'olive', 'grey'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['tshirt', 'shirt', 'jacket'],
        trendScore: 9,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/7fxy0b.png',
        buyUrl: 'https://www.myntra.com/trousers/snitch/snitch-men-black-mid-rise-relaxed-fit-cargo-trousers/34740806/buy'
      },
      //jeans
      {
        name: 'HIGHLANDER Men Black Slim Fit Mid-Rise Clean Look Stretchable Jeans',
        gender: "men",
        category: 'jeans',
        categoryGroup: 'lower',
        color: 'black',
        fit: 'slim',
        occasion: ['casual'],
        price: 610,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'mustard', 'dark pink', 'maroon'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['shirt', 'tshirt', 'casual shirt'],
        trendScore: 8,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/ug20xh.png',
        buyUrl: 'https://www.myntra.com/jeans/highlander/highlander-men-black-slim-fit-mid-rise-clean-look-stretchable-jeans/8706061/buy'

      },
      {
        name: 'Louis Philippe Jeans Men Navy Blue Slim Fit Mid-Rise Clean Look Stretchable Jeans',
        gender: "men",
        category: 'jeans',
        categoryGroup: 'lower',
        color: 'navy',   // real blue shade used in jeans
        fit: 'slim',
        occasion: ['casual'],
        price: 2999,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'mustard', 'olive', 'black'],
        targetBodyType: 'average',
        pattern: 'solid',
        compatibleTypes: ['shirt', 'tshirt', 'casual shirt'],
        trendScore: 9,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/bnb6df.png',
        buyUrl: 'https://www.myntra.com/jeans/louis2bphilippe2bjeans/louis-philippe-jeans-men-navy-blue-slim-fit-mid-rise-clean-look-stretchable-jeans/14135022/buy'
      },
      //tshirt
      {
        name: 'Van Heusen Innerwear Men Black Solid Lounge T-shirt',
        gender: "men",
        category: 'tshirt',
        categoryGroup: 'upper',
        color: 'black',
        fit: 'regular',
        occasion: ['casual'],
        price: 485,
        styleCategory: 'safe',
        compatibleColors: ['white', 'navy', 'grey', 'mustard'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'short',
        compatibleTypes: ['jeans', 'pant', 'shorts', 'cargo', 'joggers', 'trouser'],
        trendScore: 8,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/r9qa9k.png',
        buyUrl: 'https://www.myntra.com/lounge-tshirts/van+heusen+innerwear/van-heusen-innerwear-men-black-solid-lounge-tshirts/21366424/buy'

      },
      {
        name: 'H&M Men White Solid Cotton Pure Cotton T-shirt Regular Fit',
        gender: "men",
        category: 'tshirt',
        categoryGroup: 'upper',
        color: 'white',
        fit: 'regular',
        occasion: ['casual'],
        price: 499,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'grey', 'olive'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'short',
        compatibleTypes: ['jeans', 'pant', 'shorts', 'cargo', 'joggers', 'trouser'],
        trendScore: 7,
        season: 'summer',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/dbhwug.png',
        buyUrl: 'https://www.myntra.com/tshirts/h&m/hm-men-white-solid-cotton-pure-cotton-t-shirt-regular-fit/11468714/buy'
      },
      {
        name: 'Levis Men Red Blue Soft Pure Cotton Round Neck T-shirt',
        gender: "men",
        category: 'tshirt',
        categoryGroup: 'upper',
        color: 'red',
        fit: 'regular',
        occasion: ['casual'],
        price: 636,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'black'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'short',
        compatibleTypes: ['jeans', 'pant', 'shorts', 'cargo', 'joggers', 'trouser'],
        trendScore: 8,
        season: 'summer',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/g5x6o4.png',
        buyUrl: 'https://www.myntra.com/lounge-tshirts/levis/levis-men-soft-pure-cotton-round-neck-half-sleeve-tshirt/12027424/buy'
      },
      {
        name: 'Levis Men Grey Soft Pure Cotton Round Neck T-shirt',
        gender: "men",
        category: 'tshirt',
        categoryGroup: 'upper',
        color: 'grey',
        fit: 'regular',
        occasion: ['casual'],
        price: 611,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'white'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'short',
        compatibleTypes: ['jeans', 'pant', 'shorts', 'cargo', 'joggers', 'trouser'],
        trendScore: 8,
        season: 'summer',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/nxcqks.png',
        buyUrl: 'https://www.myntra.com/lounge-tshirts/levis/levis-men-soft-pure-cotton-round-neck-half-sleeve-tshirt/12027428/buy'
      },
      {
        name: 'HRX by Hrithik Roshan Men Olive Green Solid Bio-Wash Running T-shirt',
        gender: "men",
        category: 'tshirt',
        categoryGroup: 'upper',
        color: 'olive',
        fit: 'regular',
        occasion: ['casual'],
        price: 279,
        styleCategory: 'bold',
        compatibleColors: ['black', 'navy', 'grey'],
        targetBodyType: 'athletic',
        pattern: 'solid',
        sleeveLength: 'short',
        compatibleTypes: ['jeans', 'pant', 'shorts', 'cargo', 'joggers', 'trouser'],
        trendScore: 9,
        season: 'summer',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/7eduts.png',
        buyUrl: 'https://www.myntra.com/tshirts/hrx-by-hrithik-roshan/hrx-by-hrithik-roshan-men-olive-green-solid-bio-wash-running-tshirt/11999496/buy'
      },
      //casual shirt
      {
        name: 'Hubberholme Men Navy Blue Regular Fit Solid Casual Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'navy',
        fit: 'regular',
        occasion: ['casual'],
        price: 999,
        styleCategory: 'safe',
        compatibleColors: ['grey', 'white', 'mustard'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['jeans', 'pant', 'cargo'],
        trendScore: 7,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/s29o81.png',
        buyUrl: 'https://www.myntra.com/shirts/hubberholme/hubberholme-men-navy-blue-regular-fit-solid-casual-shirt/11304610/buy'
      },
      {
        name: 'Roadster Men Grey Solid Regular Fit Cotton Casual Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'grey',
        fit: 'regular',
        occasion: ['casual'],
        price: 579,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'violet'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['jeans', 'pant'],
        trendScore: 8,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/5cse25.png',
        buyUrl: 'https://www.myntra.com/shirts/roadster/roadster-men-grey-solid-regular-fit--cotton-casual-shirt/15557630/buy'
      },
      {
        name: 'Black Coffee Men Maroon Slim Fit Solid Casual Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'maroon',
        fit: 'slim',
        occasion: ['casual'],
        price: 1649,
        styleCategory: 'trendy',
        compatibleColors: ['beige', 'brown', 'black'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['jeans', 'pant'],
        trendScore: 9,
        season: 'all',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/unsaeu.png',
        buyUrl: 'https://www.myntra.com/shirts/blackcoffee/black-coffee-men-maroon-slim-fit-solid-casual-shirt/5523545/buy'
      },
      {
        name: 'Bene Kleed Men Olive Double Pocket Regular Fit Pure Cotton Casual Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'olive',
        fit: 'regular',
        occasion: ['casual'],
        price: 923,
        styleCategory: 'safe',
        compatibleColors: ['brown', 'navy', 'white'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'jeans'],
        trendScore: 8,
        season: 'summer',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/6yokd3.png',
        buyUrl: 'https://www.myntra.com/shirts/bene+kleed/bene-kleed-men-olive-double-pocket-regular-fit-pure-cotton-casual-shirt/34373264/buy'
      },
      //shirt
      {
        name: 'Van Heusen Men White Slim Fit Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'white',
        fit: 'slim',
        occasion: ['formal'],
        price: 2199,
        styleCategory: 'safe',
        compatibleColors: ['black', 'navy', 'grey', 'brown'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 7,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/3ad0js.png',
        buyUrl: 'https://www.myntra.com/shirts/van-heusen/van-heusen-men-white-slim-fit-formal-shirt/15271372/buy'
      },

      {
        name: 'Louis Philippe Men Black Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'black',
        fit: 'regular',
        occasion: ['formal'],
        price: 2599,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'navy'],
        targetBodyType: 'athletic',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 8,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/76de7x.png',
        buyUrl: 'https://www.myntra.com/shirts/louisphilippe/louis-philippe-men-black-formal-shirt/18351604/buy'
      },

      {
        name: 'Van Heusen Men Navy Blue Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'navy',
        fit: 'regular',
        occasion: ['formal'],
        price: 3686,
        styleCategory: 'safe',
        compatibleColors: ['white', 'grey', 'mustard', 'brown'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 8,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/3hp7tn.png',
        buyUrl: 'https://www.myntra.com/shirts/van2bheusen/van-heusen-men-navy-blue-formal-shirt/18654998/buy'
      },


      {
        name: 'METAL Men Grey Slim Fit Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'grey',
        fit: 'slim',
        occasion: ['formal'],
        price: 1921,
        styleCategory: 'safe',
        compatibleColors: ['white', 'black', 'brown'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 7,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/7slgyo.png',
        buyUrl: 'https://www.myntra.com/shirts/metal/metal-men-grey-slim-fit-opaque-formal-shirt/15914176/buy'
      },

      {
        name: 'Raymond Men Maroon Slim Fit Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'maroon',
        fit: 'slim',
        occasion: ['formal'],
        price: 1899,
        styleCategory: 'safe',
        compatibleColors: ['beige', 'brown', 'black', 'white'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 9,
        season: 'winter',
        isTrending: true,
        imageUrl: 'https://files.catbox.moe/1bj6d2.png',
        buyUrl: 'https://www.myntra.com/shirts/raymond/raymond-men-maroon-slim-fit-solid-formal-shirt/10620718/buy'
      },



      {
        name: 'T.M.Lewin Men Light Blue Formal Shirt',
        gender: "men",
        category: 'shirt',
        categoryGroup: 'upper',
        color: 'light blue',
        fit: 'regular',
        occasion: ['formal'],
        price: 3699,
        styleCategory: 'safe',
        compatibleColors: ['navy', 'grey', 'black'],
        targetBodyType: 'average',
        pattern: 'solid',
        sleeveLength: 'long',
        compatibleTypes: ['pant', 'trouser'],
        trendScore: 8,
        season: 'all',
        isTrending: false,
        imageUrl: 'https://files.catbox.moe/okz4x3.png',
        buyUrl: 'https://www.myntra.com/shirts/tmlewin/tmlewin-light-blue-formal-shirt/861796/buy'
      },
      {
        name: "GRACIT Women Black Ankle-Length Leggings",
        gender: "women",
        category: "legging",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["casual", "festive"],
        price: 449,
        styleCategory: "safe",
        compatibleColors: ["white", "grey", "beige"],
        compatibleTypes: ["kurti", "long_top"],
        trendScore: 8,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/4xnjhj.png",
        buyUrl: "https://www.myntra.com/leggings/gracit/gracit-women-black-leggings/19253528/buy"
      },
      {
        name: "ELLEVEN Women Solid Leggings",
        gender: "women",
        category: "legging",
        categoryGroup: "lower",
        color: "maroon",
        fit: "regular",
        occasion: ["casual"],
        price: 599,
        styleCategory: "safe",
        compatibleColors: ["black", "white", "gold"],
        compatibleTypes: ["kurti", "long_top"],
        trendScore: 7,
        season: "all",
        isTrending: false,
        imageUrl: "https://files.catbox.moe/1j8prp.png",
        buyUrl: "https://www.myntra.com/leggings/elleven/elleven-women-leggings/22808844/buy"
      },
      {
        name: "H&M Women High-Waisted Black Leggings",
        gender: "women",
        category: "legging",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["casual"],
        price: 699,
        styleCategory: "safe",
        compatibleColors: ["white", "navy", "grey"],
        compatibleTypes: ["kurti", "long_top"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/32ksm9.png",
        buyUrl: "https://www.myntra.com/Leggings/H&M/HM-Women-High-Waisted-Leggings/24320272/buy"
      },
      {
        name: "Shsuvia Pack of 2 Ankle Length Leggings",
        gender: "women",
        category: "legging",
        categoryGroup: "lower",
        color: "beige",
        fit: "skinny",
        occasion: ["casual"],
        price: 599,
        styleCategory: "safe",
        compatibleColors: ["black", "white"],
        compatibleTypes: ["kurti", "long_top"],
        trendScore: 8,
        season: "summer",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/s7891p.png",
        buyUrl: "https://www.myntra.com/Leggings/Avaasa+Buy+Shruthi/Pack-of-2-Shsuvia-Ankle-Length-Leggings-for-women/35225421/buy"
      },
      {
        name: "Next Women Black High-Waisted Leggings",
        gender: "women",
        category: "legging",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["casual"],
        price: 1299,
        styleCategory: "safe",
        compatibleColors: ["white", "grey"],
        compatibleTypes: ["kurti", "long_top"],
        trendScore: 7,
        season: "all",
        isTrending: false,
        imageUrl: "https://files.catbox.moe/z4anqi.png",
        buyUrl: "https://www.myntra.com/leggings/next/next-women-black-leggings/1882090/buy"
      },

      // PALAZZO (category: "palazzo")
      {
        name: "INDYA Women Blue & Green Striped Palazzo Pants",
        gender: "women",
        category: "palazzo",
        categoryGroup: "lower",
        color: "blue",
        fit: "regular",
        occasion: ["casual", "festive"],
        price: 899,
        styleCategory: "ethnic",
        compatibleColors: ["white", "gold", "beige"],
        compatibleTypes: ["kurti", "top", "heels"],
        trendScore: 9,
        season: "summer",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/hu6k4t.png",
        buyUrl: "https://www.myntra.com/palazzos/indya/indya-women-blue--green-striped-straight-palazzo-pants/15138050/buy"
      },
      {
        name: "Mlada Women Mid Rise Regular Fit Casual Palazzo",
        gender: "women",
        category: "palazzo",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["casual"],
        price: 799,
        styleCategory: "safe",
        compatibleColors: ["white", "beige"],
        compatibleTypes: ["kurti", "top", "heels"],
        trendScore: 8,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/fruv92.png",
        buyUrl: "https://www.myntra.com/palazzos/mlada/mlada-women-mid-rise-regular-fit-casual-palazzo-pants-/31418952/buy"
      },
      {
        name: "Sangria Women Embroidered Palazzo Pants",
        gender: "women",
        category: "palazzo",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["festive"],
        price: 537,
        styleCategory: "ethnic",
        compatibleColors: ["gold", "cream", "white"],
        compatibleTypes: ["kurti", "top", "heels"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/g2ss2t.png",
        buyUrl: "https://www.myntra.com/palazzos/sangria/sangria-women-embroidered-schiffli-palazzos/21648040/buy"  // real similar link
      },
      {
        name: "Vivika Women Flared Printed Palazzos",
        gender: "women",
        category: "palazzo",
        categoryGroup: "lower",
        color: "cream",
        fit: "regular",
        occasion: ["festive"],
        price: 799,
        styleCategory: "ethnic",
        compatibleColors: ["gold", "beige"],
        compatibleTypes: ["kurti", "top", "heels"],
        trendScore: 7,
        season: "all",
        isTrending: false,
        imageUrl: "https://files.catbox.moe/59nixc.png",
        buyUrl: "https://www.myntra.com/palazzos/vivika/vivika-women-flared-free-size-relaxed-fit-daily-wear-palazzo-/35961700/buy"
      },
      {
        name: "Biba Women Red Solid Palazzo",
        gender: "women",
        category: "palazzo",
        categoryGroup: "lower",
        color: "red",
        fit: "regular",
        occasion: ["casual", "festive"],
        price: 999,
        styleCategory: "ethnic",
        compatibleColors: ["black", "gold"],
        compatibleTypes: ["kurti", "top", "heels"],
        trendScore: 8,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/bduap5.png",
        buyUrl: "https://www.myntra.com/palazzos/biba/biba-women-palazzos/32750722/buy"
      },

      // JEANS (category: "jeans")
      {
        name: "ZUYA Women Ice Blue Straight Fit Jeans",
        gender: "women",
        category: "jeans",
        categoryGroup: "lower",
        color: "blue",
        fit: "straight",
        occasion: ["casual"],
        price: 899,
        styleCategory: "safe",
        compatibleColors: ["white", "black", "grey"],
        compatibleTypes: ["shirt", "tshirt", "top", "hoodie", "blazer"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/7z3p0j.png",
        buyUrl: "https://www.myntra.com/jeans/zuya/zuya-women-ice-blue-straight-fit-women-jeans-timeless-casual-cool/32622862/buy"
      },
      {
        name: "Roadster Women Baggy Wide Leg High-Rise Jeans",
        gender: "women",
        category: "jeans",
        categoryGroup: "lower",
        color: "black",
        fit: "wide",
        occasion: ["casual"],
        price: 1299,
        styleCategory: "safe",
        compatibleColors: ["white", "grey", "olive", "pink"],
        compatibleTypes: ["shirt", "tshirt", "top", "hoodie", "blazer"],
        trendScore: 8,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/fm5m41.png",
        buyUrl: "https://www.myntra.com/jeans/roadster/the-roadster-life-co-women-baggy-wide-leg-high-rise-heavy-fade-jeans/31027870/buy"
      },
      {
        name: "StyleCast Women Blue Regular Fit Jeans",
        gender: "women",
        category: "jeans",
        categoryGroup: "lower",
        color: "blue",
        fit: "regular",
        occasion: ["casual"],
        price: 799,
        styleCategory: "safe",
        compatibleColors: ["white", "black"],
        compatibleTypes: ["shirt", "tshirt", "top"],
        trendScore: 7,
        season: "all",
        isTrending: false,
        imageUrl: "https://files.catbox.moe/g3nr21.png",
        buyUrl: "https://www.myntra.com/jeans/stylecast/stylecast-women-jeans/31695734/buy"
      },
      {
        name: "American Eagle Women Slim Fit Jeans",
        gender: "women",
        category: "jeans",
        categoryGroup: "lower",
        color: "black",
        fit: "slim",
        occasion: ["casual"],
        price: 2499,
        styleCategory: "trendy",
        compatibleColors: ["white", "grey"],
        compatibleTypes: ["shirt", "tshirt", "top", "hoodie"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/qb6zs1.png",
        buyUrl: "https://www.myntra.com/jeans/americaneagleoutfitters/american-eagle-outfitters-women-jeans/33446887/buy"
      },
      {
        name: "Trendyol Women Cropped Regular Fit Jeans",
        gender: "women",
        category: "jeans",
        categoryGroup: "lower",
        color: "brown",
        fit: "regular",
        occasion: ["casual"],
        price: 1199,
        styleCategory: "safe",
        compatibleColors: ["white", "black"],
        compatibleTypes: ["shirt", "tshirt", "top"],
        trendScore: 8,
        season: "summer",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/1h7qyk.png",
        buyUrl: "https://www.myntra.com/jeans/trendyol/trendyol-women-jeans/32412543/buy"
      },

      // CARGO PANT (category: "cargo_pant")
      {
        name: "Street By Tokyo Talkies Women Relaxed Fit Cargo Pants",
        gender: "women",
        category: "cargo_pant",
        categoryGroup: "lower",
        color: "pink",
        fit: "relaxed",
        occasion: ["casual"],
        price: 969,
        styleCategory: "trendy",
        compatibleColors: ["black", "white", "beige"],
        compatibleTypes: ["tshirt", "crop_top", "sneakers"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/ph6s3c.png",
        buyUrl: "https://www.myntra.com/trousers/streetbytokyotalkies/street-by-tokyo-talkies-women-relaxed-fit-cargo-pants-with-flap-pockets/31968999/buy"
      },
      {
        name: "Styli Women Black Pocket Detail Cargo Pants",
        gender: "women",
        category: "cargo_pant",
        categoryGroup: "lower",
        color: "black",
        fit: "regular",
        occasion: ["casual"],
        price: 999,
        styleCategory: "safe",
        compatibleColors: ["white", "olive"],
        compatibleTypes: ["tshirt", "crop_top", "sneakers"],
        trendScore: 8,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/pmobxu.png",
        buyUrl: "https://www.myntra.com/trousers/styli/styli-women-black-pocket-detail-cargo-pants/18838348/buy"
      },

      // SAREE (category: "saree")
      {
        name: "VANAKARA Ethnic Motifs Zari Kanjeevaram Saree",
        gender: "women",
        category: "saree",
        categoryGroup: "onepiece",
        color: "gold",
        fit: "regular",
        occasion: ["festive", "wedding"],
        price: 3499,
        styleCategory: "ethnic",
        compatibleColors: ["red", "maroon", "cream"],
        compatibleTypes: ["blouse", "heels", "jewelry"],
        trendScore: 9,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/grd5gm.png",
        buyUrl: "https://myntra.com/sarees/vanakara/vanakara-ethnic-motifs-woven-design-zari-kanjeevaram-saree/27046126/buy"
      },
      {
        name: "Pionex Woven Design Zari Banarasi Saree",
        gender: "women",
        category: "saree",
        categoryGroup: "onepiece",
        color: "green",
        fit: "regular",
        occasion: ["festive", "wedding"],
        price: 6999,
        styleCategory: "ethnic",
        compatibleColors: ["gold", "black"],
        compatibleTypes: ["blouse", "heels", "jewelry"],
        trendScore: 10,
        season: "all",
        isTrending: true,
        imageUrl: "https://files.catbox.moe/rg5hdu.png",
        buyUrl: "https://myntra.com/sarees/pionex/pionex-woven-design-zari-pure-silk-banarasi-saree/26977562/buy"
      }
    ];

    await Product.insertMany(sampleProducts);
    console.log('✅ 50 REAL products with REAL buy URLs inserted!');

    // Sample user & profile
    const sampleUsers = [{ name: 'Test User', email: 'test@example.com', password: '123', preferences: { colors: ['black'], fit: 'slim', budget: 'medium', occasions: ['formal'] } }];
    const insertedUsers = await User.insertMany(sampleUsers);

    const sampleProfiles = [{
      userId: insertedUsers[0]._id,
      dominantColors: ['black'],
      preferredFit: 'slim',
      budgetRange: 'medium',
      occasionFrequency: new Map([['formal', 70], ['casual', 30]]),
      experimentalLevel: 'safe',
      styleCluster: 'Minimal Formal'
    }];
    await StyleProfile.insertMany(sampleProfiles);

    mongoose.connection.close();
    console.log('Seeding complete! 🎉');
  })
  .catch(err => {
    console.error('Seeding error:', err);
    mongoose.connection.close();
  });